### ISSUE TITLE
Half-Lambert Lighting and Vehicles

### ISSUE THREAD

**Issue by DoomedNerd** [RobertBeckebans/RBDOOM-3-BFG#220]
I'm brand new to RBDoom-3-BFG and the Doom 3 modding scene in general. I've successfully built several RBDoom-3-BFG branches with VS10 but can't seem to get a build with the Half Lambert lighting enabled. I use the v1.2 mod launcher from Motorsep's HD tutorial, and the mega hd bundle that is included via links. I'm not sure how to activate the Half Lambert lighting... and so everything is really dark like in the vanilla Doom 3 BFG. The lighting works, but with full Lambert shading. Does anyone know how I can get Half-Lambert lighting to work for RBDoom-3-BFG?

The vehicles demo from the old Doom 3 SDK loads up with RBDoom-3-BFG (soft shadows enabled turns off shadows for some reason), but when I bind a key to "_impulse40" via the console command "bind KEY _impulse40" I get an error message telling me that there is no command called _impulse40. The Read Me file for the vehicle demo says that this command is used for entering and exiting the vehicle, so that part doesn't work for me. I'm trying to follow the instructions in the Read Me, but it's not working to let me enter the vehicle.. Does anyone know how I might get this to work for RBDoom-3-BFG? 

Also, I like RBDoom-3-BFG :)

**Comment by RobertBeckebans** [comment]
The HL2 style lighting can be switched with r_useHalfLambertLighting 1 or 0 and then reloadShaders.
It is enabled by default.

**Comment by DoomedNerd** [comment]
Thanks Robert, I love your project here, but for reasons unknown, the shadows are just as dark as they were in the vanilla D3 bfg. At least the soft shadows work for me, which is a pretty cool feature.

**Comment by BielBdeLuna** [comment]
first change the variable and then type "relaodShaders" and intro

on the shadows being dark it only depends on the ambient light in the scene, the half-Lambert doesn't magically change the ambient light, but how the diffuse gets illuminated

**Comment by DoomedNerd** [comment]
Okay, I see what you're talking about. I noticed that the NPC's faces are half-lambert illuminated. I was hoping that this feature would work, and thanks for helping me understand the finer nuances of this shading technique. You can consider this "issue" (i.e. my ignorance) closed. 

But if you'd like to educate me one step further, could you explain how I could get some slight global ambiance to lighten up Doom 3? I'd like to have most of the dark areas of maps to be like those in games like half-life 2 or Resident Evil 4. Some scenes in those games had true black areas (or 0 ambiance I think) were a flashlight was needed, but most other areas you could see in low light if you raised the brightness setting a bit. This is how light seems to appear to me in the real world, because many surfaces of real world objects do reflect light to some degree (and certainly shiny space station bulkhead metal would, I think), and end up sharing light towards surface areas of relatively close objects that aren't directly in the path of a light ray, or facing opposite of a ray's path. And plus, all that darkness scares the crap out of me, heh.

**Comment by BielBdeLuna** [comment]
HL2 uses static light-maps for their lightning, it creates a ambient light term (a term is a stage in the light equation) that is applied per-surface in the map (in fact is a texture that gets multiplied to the diffuse map, and that includes shadows, over-brightness, and global illumination) and it's static, besides this also it uses light proves (cube-maps) in specific places in order to enhance the scene reflections (so your weapon reflects the environment (although it's not a very advanced technique that most of the time looks out of place)

anyway D3 can't do any of this without modding.

D3 can do ambient lights (which occupy a cuboid space, or a parallelepiped space, with a texture controlling it's full colour and dispersion) which usually adds on the diffuse term of the scene (although it depends on it's shader material definition)

you could have a general ambient level by two methods: you could engulf the whole level (or parts where you need the ambient level) within the ambient light space

or you could mod the game in order to include the ambient light as a stage for every map, and so control the ambient light level with a cvar (like in sikkmod) but for this you will need to mod the game.

as you see d3 doesn't have global illumination, you can fake it with several local ambient maps and normal lights but it might come at a cost of dropping the frame-rate.

newer approaches for GI (global illumination) often involve static scenes ( or at least static walls ) or heavy preprocessing and in-game processing of the scene.

**Comment by DoomedNerd** [comment]
Hey thanks BielBdeLuna. Very informative :+1:
