### ISSUE TITLE
Annoying, Ugly Shadow Lines

### ISSUE THREAD

**Issue by TyrannoWright** [RobertBeckebans/RBDOOM-3-BFG#237]
After the issue of the colored shadows, I'm getting these lines in the shadows that make some characters look ugly and textures seem annoying along with a framerate drop.

![rbdoom3bfg exe_2015-07-22-21-05-07-387](https://cloud.githubusercontent.com/assets/10506744/8837361/daf612a8-307a-11e5-921d-c060e70218ca.jpg)
![rbdoom3bfg exe_2015-07-22-21-06-06-556](https://cloud.githubusercontent.com/assets/10506744/8837365/e005a9d4-307a-11e5-99b9-0165aee4275f.jpg)

**Comment by RobertBeckebans** [comment]
Yeah it is the typical shadow mapping acne problem. I couldn't get around
this problem yet.

2015-07-22 23:07 GMT+02:00 TyrannWright <notifications@github.com>:

**Comment by TyrannWright** [comment]
Shame. Let's hope for a fix soon...

**Comment by nbohr1more** [comment]
Maybe fixable?

https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/203

**Comment by Yetta1** [comment]
@TyrannWright I've noticed that BFG seems to have an issue with gamma correction, often colorizing the textures with purple/green tints which is why things seem a bit off, the only way around it is by setting custom gamma settings in the graphics card driver control panel.

@RobertBeckebans This artifact also appears in Blender's game engine when using shadows, usually improved when using the variance method and increasing the raycast length as well as sample resolution. Not sure if it is the same for the soft shadows you've written.

**Comment by RobertBeckebans** [comment]
Found something interesting that might help: http://www.dissidentlogic.com/old/images/NormalOffsetShadows/GDC_Poster_NormalOffset.png

**Comment by Yetta1** [comment]
Interesting. Near the end of the article, they spoke of post process filtering. Maybe a cheap blur on the shadow pass?

**Comment by QcSamuel** [comment]
any news on this ?

**Comment by Calinou** [comment]
I suppose shadow bias could be increased in the meantime. This will cause shadows to "peter-pan" noticeably around their caster though.

**Comment by QcSamuel** [comment]
i wonder if the completed vulkan renderer could fix this ?

**Comment by Calinou** [comment]
> i wonder if the completed vulkan renderer could fix this ?

Vulkan doesn't resolve this in itself. This can also be fixed in an OpenGL renderer by implementing shadow normal offset bias.

**Comment by RobertBeckebans** [comment]
This has been fixed in the new DX12 / Vulkan backends using temporal anti aliasing.
