### ISSUE TITLE
AA not working, lighting bug

### ISSUE THREAD

**Issue by ZaxxerDog** [RobertBeckebans/RBDOOM-3-BFG#283]
I'l just copy-paste my comment from the Steam forums:
http://steamcommunity.com/app/208200/discussions/0/487876568229181054/#p3
This stuff happens with the Hi Def mod but I didn't try RBDoom3 without that so it can be an issue with the engine.

"Got it working somehow, looks like a fresh install did the trick but there are still some minor issues:
- There is a strange blue glow applied to all light sources and it has to be a bug because sometimes it disappears. Here's what I'm talking about:
  http://i.imgur.com/Yi6LNuu.jpg
- AA is either messed up or not working: that last screenshot was taken with 8x MSAA yet the edges are jaggy as hell
- I don't see the LOD slider anymore yet it should be there to fine-tune image quality (too much is bad, too little is equally bad because it results in distorted, "jaggy" textures).

Edit: Based on a comparison between the original and the modded version I can confirm that AA is not working in RBDoom3. The lighting bug also doesn't exist of course. It's a shame that people have to build source ports in order for simple texture mods to work, that's a hard job."

**Comment by RobertBeckebans** [comment]
Simply open the console and type r_useHDR 0. There will be new menu options soon where you can disable HDR. The only anti aliasing technique that works with HDR is SMAA.

**Comment by ZaxxerDog** [comment]
Thanks, worked like a charm and it "solved" the strange blue light shafts too. Are those bugs or is this just how HDR was intended to work?

**Comment by aFoxNamedMorris** [comment]
The effect is supposed to be lens flares. They can be tweaked to be more comfortable, or disabled.

**Comment by ZaxxerDog** [comment]
Honestly I suggest disabling those by default if that can be done without getting rid of HDR. I could get the need for a lens flare effect but the thing is at its current for this just breaks the lighting because it gets applied even to shiny surfaces that are not light sources (e.g. metal boxes).

**Comment by aFoxNamedMorris** [comment]
That's why you tweak the values. And FYI lens flares work that way IRL. if it's bright, light source or not, it creates a flare in the lens. If you want in-game flares just for light sources or super bright areas, change 'r_hdrContrastThreshold' to 15 or 18. To tone down flares' intensity, set 'r_hdrContrastOffset' to between 50 and 100.

**Comment by ZaxxerDog** [comment]
Cool, will try it once AA will work with HDR... but anyway why aren't the more "tame" options are the default values? Not in 20 years of gaming have I seen such an obnoxious and "fake" use of it in any kind of professionally made videogame. My first thought was "wow, what a bug" so frankly finding out that it was intentional sounds pretty ridiculous at first. That's not how you're supposed to do those things though sure, that's why modding exist.

**Comment by aFoxNamedMorris** [comment]
Set 'r_antialiasing' to 1. This allows you to have decent AA with HDR.

**Comment by aFoxNamedMorris** [comment]
AA does work with HDR. You have to use a non-MSAA setting. So
'r_antialiasing 1'. This sets the AA to SMAA which works with HDR... right
now.

**Comment by BielBdeLuna** [comment]
@ZaxxerDog the pixel shader for the bloom is there you can change it however you want, and please don't compare triple A games art with art produced by a single individual it's not fare, tripple A games have lots of people doing the art and getting paid for it.

**Comment by TheVoodoo** [comment]
I would love to see those lensflares less blue, they look a bit weird. If they were more white i guess they would fit better to the lightsource. Or add a bright bloom to the center of lightsources... Here's a sample of a lensflare from Fallout 4 i really like... http://staticdelivery.nexusmods.com/mods/1151/images/2567-0-1448917381.png

**Comment by aFoxNamedMorris** [comment]
Biel is working on that.

**Comment by BielBdeLuna** [comment]
we already have that a little bit smaller, and the radial (in fact is a star) blooming too, in fact the light bug that @ZaxxerDog showed in that picture is this same effect but at a smaller scale

At the moment I'd like to implement an inversion of the over-bright pixels but I don't know how to get the screen total resolution in X and Y and sum it's inverted positions in order to get it to work.

**Comment by RobertBeckebans** [comment]
My implementation is chromatic bloom which burns out into a bluish effect based on the most bright pixels. I don't care much about how games do stuff because you can learn from many games how to not do it.
If you don't like it then simply turn it off. Usually GFX programmers copy some ideas from some others and somehow completely wrong light calculations make it into 90% of all games like the really weird UT3 style HDR tone mapping in almost all UE3 based games.

This is how chromatic bloom looks in movies and it is also my goal how I want to see it in this futuristic game: http://imgur.com/a/rYogg

**Comment by RobertBeckebans** [comment]
And please note that the High-Def Mod uses the current master branch here on Github. This is a preview version and no stable official RBDOOM-3-BFG release.

**Comment by DanielGibson** [comment]
Some of those movie screenshots look like the movie file is corrupted :-P

**Comment by y2keeth** [comment]
yes get the newest version of rbdoom3bfg for my hidef mod please keep trying to get everyone to download it
