### ISSUE TITLE
Mac OS X support... 

### ISSUE THREAD

**Issue by Kamastein** [RobertBeckebans/RBDOOM-3-BFG#296]
What's the status of this? Has it been dropped? Are there going to be binaries made available at some point? I upgraded to El Capitan recently and decided giving compiling a go but can't make heads or tails of it. Not my forte..

**Comment by JanSimek** [comment]
Dude, there are already two open bug tickets about OS X support, so there was no need to open another one.

The OS X port has not been dropped by Robert yet, but no one has worked on it since I sent in my patches two years ago. I have played it on linux since then and only today tried if it still works on OS X. It doesn't. It still compiles (although not with Xcode), however, when you load the first mission you get: ```caught OpenGL error: GL_INVALID_OPERATION in file /Users/.../Development/RBDOOM-3-BFG/neo/renderer/RenderSystem.cpp line 796`` error.

**Comment by MoridinBG** [comment]
It works with a small tweak. On 10.12.2 in posix_public.h the clk_id_t enum entries conflict with /usr/include/time.h
This is weird, because posix_public.h defines them as CLOCK_REALTIME, etc and in time.h they are _CLOCK_REALTIME (notice the underscore), but renaming CLOCK_REALTIME to  CLOCK__REALTIME fixes the issue and it compiles and runs ok.

But there is a big fps problem - on a 750m it barely runs at 30fps with everything disabled on 1440x900
Is it really that demanding or is it a mac os issue?
