### ISSUE TITLE
Strange texture banding

### ISSUE THREAD

**Issue by donizettilorenzo** [RobertBeckebans/RBDOOM-3-BFG#312]
I think it's a bug:

https://postimg.org/image/wr7vh6usx/

About the grain film: can you add an option to turn it on/off ?

**Comment by Yetta1** [comment]
@donizettilorenzo Hi, the banding is caused by the soft shadows if I remember correctly. I think it had something to do with clipping distance. I had a workaround for it a while back, but will have to figure that out again. There should be a cvar in the console for the filmgrain, just open the console "~" and type in "listcvars", it should list all the engine commands, scroll up with the mouse, I think most of the rendering starts with "r_". I don't have filmgrain on with my version, it might be because I disabled it on the vanilla BFG. Sorry I couldn't be of more help, it's been a while since i've played on the RB engine.
