### ISSUE TITLE
Couldn't load image: textures/loadingicon2

### ISSUE THREAD

**Issue by ghost** [RobertBeckebans/RBDOOM-3-BFG#320]
Hello,
I've tried both the latest release and the latest revision of rbdoom3bfg on GNU/Linux x86_64 and they both refuses to launch with the following error.

```
------- Initializing renderSystem --------
WARNING: Couldn't load image: textures/loadingicon2 : textures/loadingicon2#__0200
WARNING: Couldn't load image: textures/loadingicon3 : textures/loadingicon3#__0200
Sys_Error: _default material not found
AL lib: (EE) alc_cleanup: 1 device not closed
```

[Complete log is available here.](http://pastebin.com/raw/puBTsCSW)

I've downloaded Doom 3 BFG from Steam and all the `base/pak*.pk4` files have a correct md5 checksum.

**Comment by TheVoodoo** [comment]
The Doom3 BFG Edition doesn't use any *.pk4 files. Seems to me you're trying to run RBDoom3BFG with the calssic Doom3 release! That doesn't work!

**Comment by marespiaut** [comment]
I assure you that I'm using the BFG Edition from Steam.
I'll check again as soon as possible.

**Comment by Yetta1** [comment]
BFG packs all content into resource files, it's a change that came with idTech 5 which was used for Rage, BFG is a mix of idTech4/5. Have you verifed the files on steam to check if all the files are ok? Did you follow the steps in the readme on installing BFG with steamCMD on Linux?

You can also try extracting all the asset resources using the following command in the console "exec extract_resources", it will extract all the data into the base, but will increase the size almost double of the game. Then you need to tell the engine to use those files instead of the resource files by adding the following launch parameter to your shortcut. "+set fs_resourceLoadPriority 0".

**Comment by BielBdeLuna** [comment]
this last parameter should be 0 by default
