### ISSUE TITLE
Vsync doesn't properly match refresh rate

### ISSUE THREAD

**Issue by Keith94** [RobertBeckebans/RBDOOM-3-BFG#383]
Running the game @ 120 Hz with vsync enabled results in 60 FPS cap. Frame rate option is set to 120 FPS.

![rbdoom3bfg_2017_08_11_11_17_30_602](https://user-images.githubusercontent.com/5490615/29226630-8e39b412-7e87-11e7-91cd-8c3f1d630d7e.png)

**Comment by BielBdeLuna** [comment]
This seems like something that needs further attention!

**Comment by Keith94** [comment]
OK. Reopened. :)

**Comment by BielBdeLuna** [comment]
is your GPU able to generate more than 30 fps? what are your specs?

**Comment by itaranto** [comment]
My PC is kinda old, but it did handle some games at 60fps.

My specs:
OS: openSUSE Leap 15.0
CPU: Intel Core i5-2310
GPU: NVIDIA GTX 650
Driver version: NVIDIA 390.87

**Comment by BielBdeLuna** [comment]
maybe with the soft shadows and the hdr the system is not powerful enough?

**Comment by itaranto** [comment]
I'm using r_useShadowMapping = "0" and as a consequence r_useHDR = "0".
But yeah, it can be that my computer is just slow, I just mentioned it because most of the time I saw **exactly** 30 fps , no more, no less.

Anyway, 30 fps is a decent frame rate and the game works like a charm.

**Comment by itaranto** [comment]
New update, I'm running on a new machine:
AMD Ryzen 2700X + Radeon RX 570 + Mesa 18.1.7
With vsync enabled the FPS are capped at 30, with  "smart" vsync or vsync disabled, FPS are capped at 60 but I experience screen tearing.

**Comment by badsectoracula** [comment]
I have a 165Hz monitor and experience the same issue... actually i experience the issue without vsync too (120 fps mode is still visually capped at 60fps).

The issue seems to be that the game doesn't request a specific refresh rate so you get a 60Hz one. A workaround is to create an autoexec.cfg file alongside the D3BFGConfig.cfg file in your %userprofile%\Saved Games\id Software\RBDOOM 3 BFG directory with the following lines:

    set r_customWidth "2560"
    set r_customHeight "1440"
    set r_vidMode "-1"
    set r_displayRefresh "165"

(do not bother with editing the D3BFGConfig.cfg file itself, it resets to the default values after exiting)

Obviously replace the 2560 and 1440 with your own resolution and 165 with the monitor refresh rate you want (make sure your monitor supports that otherwise you'll get the default settings - ie. do not just use "120").

A better fix for this would be for video mode enumeration to also enumerate and show refresh rates in the game menu.

**Comment by RobertBeckebans** [comment]
This should be fixed with the new DX12 & Vulkan backends.
