### ISSUE TITLE
eye glasses disapper in render

### ISSUE THREAD

**Issue by suijingfeng** [RobertBeckebans/RBDOOM-3-BFG#416]
![screenshot from 2018-03-17 13-21-13](https://user-images.githubusercontent.com/10341056/37552330-f42c1780-29ed-11e8-9e66-4aa7a49df4b2.png)

**Comment by andrew-mcmahon** [comment]
Assuming that you're compiling from source.
Try adding this line to **neo/CMakeLists.txt** just below _cmake_minimum_required(VERSION 2.8)_:

`cmake_policy(SET CMP0072 NEW)` 

You'll have to then run **neo/cmake-linux-release.sh** and recompile from the build folder.
It's probably due to using the old GL libraries by default.

![screenshot_2018-08-08_09-33-40](https://user-images.githubusercontent.com/42167250/43826071-4380000a-9aee-11e8-80b7-af0b8a2831df.png)

You'll probably [run into this bug too](https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/419) and have to make the change mentioned there.

**AMD R9 285**
```
OpenGL renderer string: AMD Radeon R9 200 Series (TONGA, DRM 3.25.0, 4.17.12-arch1-1-ARCH, LLVM 6.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.1.5
OpenGL core profile shading language version string: 4.50
OpenGL version string: 3.1 Mesa 18.1.5
OpenGL shading language version string: 1.40
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.1.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

```

**Comment by suijingfeng** [comment]
@andrew-mcmahon 
I add `cmake_policy(SET CMP0072 NEW)` to the top of `neo/CMakeLists.txt`,
cmake complains 

```
CMake Error at CMakeLists.txt:5 (cmake_policy): 
Policy "CMP0072" is not known to this version of CMake.
```


 I'm using ubuntu linux and run `cmake --version` gives
```
cmake version 3.10.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
BTW,original compilation gives tons of warnings, 
the code base is just too large and complicated for novice programmer like me.
Anyway, thanks for you help.

**Comment by RobertBeckebans** [comment]
This was fixed in the PBR2 branch.
