### ISSUE TITLE
The game shows a black window and crashes

### ISSUE THREAD

**Issue by HardDie** [RobertBeckebans/RBDOOM-3-BFG#484]
cmd: rbdoom3bfg +set developer 1 +set logfile 2

Crash message:
```
...6 aas types
game initialized.
--------------------------------------
Loaded FFMPEG file: 'video/intro/introloop.bik', looping=1512x512, 30.000000 FPS, 12.000000 sec
Binarize File: '_cinematic' - reason 'generated image'
Loaded FFMPEG file: 'video/mars1.bik', looping=0512x512, 30.000000 FPS, 32.166668 sec
Binarize File: '_cinematic' - reason 'generated image'
Loaded FFMPEG file: 'video/mars_rotation.bik', looping=11567x406, 30.000000 FPS, 100.000000 sec
signal caught: Segmentation fault
si_code 128
Trying to exit gracefully..
session->GetSaveGameManager().CancelToTerminate();
soundSystem->StopAllSounds();
Stop();
```

Distro:
```
Arch Linux
```

Kernel:
```
╰─$ uname -a
Linux DELL 5.7.9-arch1-1 #1 SMP PREEMPT Thu, 16 Jul 2020 19:34:49 +0000 x86_64 GNU/Linux
ux
```

CPU:
```
model name      : Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
```

RAM:
```
╰─$ free -h
              total        used        free      shared  buff/cache   available
Mem:          7.6Gi       1.3Gi       3.6Gi       500Mi       2.6Gi       5.5Gi
Swap:            0B          0B          0B
```

Graphic Card:
```
╰─$ glinfo
GL_VERSION: 4.6 (Compatibility Profile) Mesa 20.1.3
GL_RENDERER: Mesa Intel(R) UHD Graphics (CML GT2)
GL_VENDOR: Intel
```

qconsole.log
https://pastebin.com/qE1QutDx

**Comment by marcoesposito1988** [comment]
I encountered the same problem on Manjaro. It seems to be a problem with FFMPEG, which is present in version 4.3.1 and was then fixed with this commit: https://github.com/FFmpeg/FFmpeg/commit/799fc4d732fc2515911b75fe816da2bbd20221d9. 

So I guess there is no action required in this project, and the issue can be closed. When Arch and Manjaro will update the FFMPEG package this problem will be sorted out automatically.

If you are impatient, I guess you can disable the cinematic intro somehow (I am not familiar with the project, I just wanted to get it started to play the game).

If you also feel adventurous, you can compile your own FFMPEG and make RBDOOM3 use it (like I did to bisect the FFMPEG problem). You can take a look at the [PKGBUILD](https://github.com/archlinux/svntogit-packages/blob/packages/ffmpeg/trunk/PKGBUILD) to get jump-started with FFMPEG compilation. After installing FFMPEG to a directory, you will need to make RBDOOM3 use it instead of the system one. Unfortunately the FindFFMPEG.cmake included in this project does not allow you to specify the path to the FFMPEG directory; for your purposes, you can hardcode it.

**Comment by RobertBeckebans** [comment]
FFmpeg is optional. You can also use the internal library by adding this to your cmake options: -DFFMPEG=OFF -DBINKDEC=ON

**Comment by HardDie** [comment]
> FFmpeg is optional. You can also use the internal library by adding this to your cmake options: -DFFMPEG=OFF -DBINKDEC=ON
Yes, that's work!
@marcoesposito1988 @RobertBeckebans thank you!
