### ISSUE TITLE
Add support for Mikkelsen Tangent Spaces

### ISSUE THREAD

**Issue by RobertBeckebans** [RobertBeckebans/RBDOOM-3-BFG#503]
This is well explained in 

https://medium.com/@bgolus/generating-perfect-normal-maps-for-unity-f929e673fc57
http://www.mikktspace.com/
https://github.com/mmikk/MikkTSpace/

RBDOOM-3-BFG needs an update in R_DeriveTangents to support the standard method by Morten S. Mikkelsen so new custom content looks like it should.

**Comment by BielBdeLuna** [comment]
I think one can see those strange normals on the brushes with normal map materials in the game levels too. Sometimes the specular reflection gets affected by the triangles of the bushes when it shouldn't because the two tringles that form the plain wall are in the same plane and should have the same normal, yet the light react as if the mid edge amongst the two triangles that conform a plane was a protruding ridge when it isn't.

Carmack also spoke of the "re-normalitzation issue".
