### ISSUE TITLE
Texture misaligned

### ISSUE THREAD

**Issue by runlevel5** [RobertBeckebans/RBDOOM-3-BFG#533]
#### Host specs

OS: Fedora 33 (ppc64le)
GCC: 10.2.1 20201125
glibc: 2.32

#### Compiler Options:
```
option(FORCE_COLOR_OUTPUT: ON)
option(COMPILE_COMMANDS: OFF)
option(USE_MFC_TOOLS: OFF)
option(USE_PRECOMPILED_HEADERS: ON)
option(SDL2: ON)
option(OPENAL: ON
option(FFMPEG: ON)
option(BINKDEC: OFF)
option(USE_VULKAN: ON)
option(SPIRV_SHADERC: ON)
option(ONATIVE: ON)
option(USE_SYSTEM_ZLIB: OFF)
option(USE_SYSTEM_LIBPNG: OFF)
option(USE_SYSTEM_LIBGLEW: OFF)
option(USE_SYSTEM_RAPIDJSON: OFF)
```

#### Describe

Characters of text texture are not aligned correctly

![Screenshot from 2021-02-27 22-23-05](https://user-images.githubusercontent.com/135605/109386061-347cc680-794c-11eb-90d5-866f411333ec.png)
![Screenshot from 2021-02-27 22-25-00](https://user-images.githubusercontent.com/135605/109386063-36df2080-794c-11eb-919d-342d91329863.png)

**Comment by RobertBeckebans** [comment]
Strange, it is only the A letter.

**Comment by runlevel5** [comment]
Indeed, any suggestion which part of logic might be?

**Comment by BielBdeLuna** [comment]
the "new" code for GUIs fonts maybe? the different code between doom3 BFG  and vanilla Doom3

**Comment by runlevel5** [comment]
> the "new" code for GUIs fonts maybe? the different font code and GUI code between doom3 BFG and vanilla Doom3

Could you please elaborate more on this?

**Comment by BielBdeLuna** [comment]
I guess the code bug is within:

> /neo/render/tr_frontend_guisurf.cpp

the script related to gui surfaces

or it could be in the font code in:

> /neo/render/font.h / .cpp

**Comment by runlevel5** [comment]
@BielBdeLuna I had a go at debugging the [renderer font code](https://github.com/RobertBeckebans/RBDOOM-3-BFG/blob/master/neo/renderer/Font.cpp) but could not pin point exactly the culprits. The way that I do is to print out all infos to STDOUT then compare them with that of x86_64, but I could not find anything unusual or different. Would you be able to suggest me some troubleshooting approach? Please excuse me for asking such question, I am new to game dev

**Comment by BielBdeLuna** [comment]
maybe it's the GUI code rather than the font code, those letters in the image are actually a font texture that gets sliced into the "glyphs" of every letter and placed in a two triangle rectangle mesh that has every letter that compose a message in the GUI surface, and those rectangles seem to be in the wrong places.
can you show those errors while showing the triangles? `r_showTris 1 or 2` might do the trick. if the squares are not well placed, then maybe it's not the fonts but the GUI code. other non text GUI elements do show strange behaviour? 

keep in mind though that the menus and the PDA menu are not GUIs but SWFs. but any ways, do you see strange letter-related defects while on SWFs too?

all the examples you posted at the moment are errors in GUIs not SWFs.

**Comment by runlevel5** [comment]
The PDA GUI looks okay to me

![Screenshot from 2021-03-21 10-18-10](https://user-images.githubusercontent.com/135605/111888607-0ada2b00-8a32-11eb-9993-d29a55eb82da.png)

the only GUI bug I could find is the date text alignment in the following screenshot

![Screenshot from 2021-03-21 10-18-36](https://user-images.githubusercontent.com/135605/111888621-2c3b1700-8a32-11eb-839d-d0c2902251f7.png)

**Comment by runlevel5** [comment]
FYI

![Screenshot from 2021-03-21 10-44-44](https://user-images.githubusercontent.com/135605/111888695-006c6100-8a33-11eb-9afa-1ab2c6867e93.png)
![Screenshot from 2021-03-21 10-46-11](https://user-images.githubusercontent.com/135605/111888696-019d8e00-8a33-11eb-9a1c-305221ff31ec.png)

**Comment by BielBdeLuna** [comment]
I tested the SWF with the video with the dates slashes in my build looks fine, that is it looks different than to you.
and the GUIs looked fine to me, I'm using the Master branch, OpenGL, and Linux. what Linux are you using? 

with the GUI problems:
maybe there is a difference on the underlying maths algorithms that position some of the letters (the A, but again why the A in specific and not the other letters?)
I wonder if A is the letter 0 in the list, maybe the member 0 in the letter list has something special done to it? a spacial case for the member 0?

maybe the maths algorithm has something done to it, some optimization that worked somewhere else but that damaged the letter rendering? or maybe the letter rendering had some optimization done to it that depended on a very specific maths algorithm and changing that algorithm broke the letter position?

on the SWF problems:
I don't know, it's a font problem? it's a SWF rendering problem? the thing that only seems to be clear is that it's not a structural problem in the SWF file because then I would have the same error.

**Comment by BielBdeLuna** [comment]
I see you're on PowerPC, I would look into the maths algorithms related to the GUI letter positions

**Comment by runlevel5** [comment]
@BielBdeLuna I can confirm the issue occur for both OpenGL and Vulkan renderer

I will dig in to see if there is math algorithm involved

**Comment by BielBdeLuna** [comment]
I would treat the GUI problems and the SWF problems as two separated problems though

**Comment by RobertBeckebans** [comment]
Could you try to compile RBDOOM-3-BFG with Clang instead of GCC?

**Comment by runlevel5** [comment]
> Could you try to compile RBDOOM-3-BFG with Clang instead of GCC?
@RobertBeckebans yes I have tried. Same issue

**Comment by KiralyCraft** [comment]
I can confirm this issue on Nvidia L4T

**Comment by BielBdeLuna** [comment]
A and 1 might be the first characters in a list? unless the numbers start with 0 (which they might be)

**Comment by KiralyCraft** [comment]
I am compiling master again right now, specifically 09c9f254c87e22663c6b5a52d6907fa020c0979b with the `cmake-linux-nvidia-jetson-vulkan-release.sh` from `neo`. I will attach some screenshots as well, will edit this comment to prevent spamming this thread.

**Comment by KiralyCraft** [comment]
> A and 1 might be the first characters in a list? unless the numbers start with 0 (which they might be)

Looks like it's only A and 1. Everything else seems fine for me. The exact same code works fine on x64, so I assume it's down to the specifics?

**Comment by KiralyCraft** [comment]
Also happens with W?

![ingame_again](https://user-images.githubusercontent.com/10259742/114449499-76508c00-9bdd-11eb-9a53-3c7250dd498f.png)

**Comment by BielBdeLuna** [comment]
so it's not a list of characters thing, "W" isn't the first character anywhere. Isn't it?

**Comment by KiralyCraft** [comment]
> do those characters also fail in the console?

Could you please elaborate on this part? I've never played Doom 3 before, so I'm not quite sure which console you are referring to.
Also, from what I understand, the SWF things are the interactive displays? This excludes the PDA

**Comment by KiralyCraft** [comment]
Also seems to happen for Y: 

![image](https://user-images.githubusercontent.com/10259742/114444214-430afe80-9bd7-11eb-8f7c-173bcff954b7.png)

**Comment by BielBdeLuna** [comment]
the console is heavily controlled by the c++ code, so it's not a GUI file or a SWF file.

the GUI file allows to do interactive screens within the game, this are plain text files in the .gui extension that conform a graphics interface scripting to do so. in the past ( read vanilla Doom3, Quake4, Prey ) those used to also handle the full screen graphic interfaces of all the game. but with Doom3 BFG a new system was introduced:

the SWF system (this is flash based) uses de .swf files from flash and handle just the full screen graphic user interface (the main menus, and the PDA)

So those two system are separate.
It is pretty interesting that ID provided a way to render flash based graphic user interface in it's released code under a open source licence ( flash is proprietary tech from Adobe, although there are other open source implementations) 
I think ID used flash for Rage.

**Comment by KiralyCraft** [comment]
I see, thank you so much for the clarifications. I also found more occurences about other leters, such as X and even inside the PDA. Attaching pictures

![nextdepartue](https://user-images.githubusercontent.com/10259742/114602091-e3782600-9c9e-11eb-8161-2990c1fbe672.png)
![pda](https://user-images.githubusercontent.com/10259742/114602094-e410bc80-9c9e-11eb-8519-dc5b2111f9c1.png)

**Comment by BielBdeLuna** [comment]
why the A in EMAIL (which is capital) doesn't fail the same way in the pda? or the As in ASSISTANT? there is a difference between the text written in the emails and the name of the sections in the pda?

**Comment by runlevel5** [comment]
The issue is fixed in https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/893

Great thanks @glKarin

**Comment by RobertBeckebans** [comment]
Very cool :)
