### ISSUE TITLE
Mod missing from ModDB

### ISSUE THREAD

**Issue by uaktags** [RobertBeckebans/RBDOOM-3-BFG#589]
Edit:
Sorry for the blank issue. Just reporting here that the mod is missing from ModDB.

**Comment by BielBdeLuna** [comment]
you mean you can't download it from ModDb?

**Comment by uaktags** [comment]
Yep, there are no files listed on the ModDB page linked in the readme file.

**Comment by cll00** [comment]
i try to download the lastest version form ModBD but don't appear any file

**Comment by RobertBeckebans** [comment]
That's correct. The 1.3.0 release is not public yet and there are only preview builds on Discord where I can gather feedback. I need to make a few changes to the engine and rebake the light data for like 10 maps and then it will be released on Mod DB. I already linked Mod DB in the Readme because it will be a rather hefty 4 GB download which isn't really suited for GitHub alone. However the documentation needs to be done before I can tag the whole thing for a release. Stay tuned.

**Comment by cll00** [comment]
Thanks Robert for the aclaration... really i appreciate you work with this masterpiece

**Comment by RobertBeckebans** [comment]
Guys it is released on ModDB https://www.moddb.com/mods/rbdoom-3-bfg/downloads/rbdoom-3-bfg-130
