### ISSUE TITLE
Turning off precompiled headers on Mac produces errors

### ISSUE THREAD

**Issue by tomgreen66** [RobertBeckebans/RBDOOM-3-BFG#597]
In #590 it was discussed that turning off precompiled headers seems to not work on Mac. I get the following errors in `posix_public.h` 
```
In file included from /Users/tom/Work/git/myDOOM3-BFG/neo/sys/posix/platform_osx.cpp:30:
/Users/tom/Work/git/myDOOM3-BFG/neo/sys/posix/../posix/posix_public.h:38:8: error:
      unknown type name 'glconfig_t'
extern glconfig_t glConfig;
       ^
/Users/tom/Work/git/myDOOM3-BFG/neo/sys/posix/../posix/posix_public.h:40:23: error:
      unknown type name 'sysEventType_t'
void            Posix_QueEvent( sysEventType_t type, int value, int valu...
```

as well a lot in `platform_osx.cpp` 

I added `#include "../../idlib/precompiled.h" to `posix_public.h` and fixed all the issues but SRS recommended this is quite a big change to a common posix file across many systems.  Maybe a better approach?

Would be nice to know it works on Mac I suppose but not urgent - spotted PCH is turned off due to Vulkan issues in `CMakeLists.txt` and wanted to test it to try and see if it helped with #591.  Also highlighted I had to change the `SET` command in `CMakeLists.txt` since it was overriding a `CACHE` variable with a default option - maybe change in behaviour with Cmake version.  E.g.

https://github.com/tomgreen66/DOOM-3-BFG/blob/d14b2d5f60f7a76592f2f04534acc74d593010c9/neo/CMakeLists.txt#L91-L94

**Comment by SRSaunders** [comment]
Looking at platform_linux.cpp and platform_osx.cpp the first line (line 29) in both is `#include "../../idlib/precompiled.h"`.  However, in platform_osx.cpp the line is commented out - this is causing the PCH-off problem on macOS.  If you uncomment the line, the problem should be solved.  Not sure why this was commented out before. A simple one line pull-request for platform_osx.cpp would re-enable macOS PCH-off with no impact to other platforms.

In any case, this problem is a bit academic - the benefits of PCH are significant (tested on a Core i7 iMac 2017).  I am not sure why you would want to turn PCH off.  See the build-time stats below:

1. Xcode OpenGL+BinkDec Release build with PCH **off** = 75.7 seconds (trial 1), 67.4 seconds (trial 2)
2. Xcode OpenGL+BinkDec Release build with PCH **on** = 40.2 seconds (trial 1), 38.7 seconds (trial 2)

**Comment by SRSaunders** [comment]
@tomgreen66 - In addition to the FFmpeg/BinkDec support, pull request #599 should also fix the PCH off problem on macOS.  If you want to verify it that would be great.

**Comment by SRSaunders** [comment]
@tomgreen66 - one way to easily verify this issue before closing is to build on Big Sur using the new cmake-xcode-opengl-universal.sh script.  This sets up a universal build which turns off PCH in the CMakeLists.txt file.  However, please note this universal build script assumes MacPorts install locations for openal-soft as well as availability of universal arch libraries (both libsdl2 and libopenal).  See the new README for details.  If you don't want to do this, you could simply hack the CMakeLists.txt file and turn off PCH for your test.

**Comment by SRSaunders** [comment]
This issue has been solved for a while.  Would @tomgreen66 please close.  Thanks.
