### ISSUE TITLE
Request: Disable gibbing

### ISSUE THREAD

**Issue by ROCKNROLLKID** [RobertBeckebans/RBDOOM-3-BFG#619]
I would like to be able to disable gibbing from when you shot bodies on the ground and such. Is there a way to do this already?

**Comment by y2keeth** [comment]
this will do that you dont need hidef eitherUngibbable mod for Doom 3 BFG Hi Def addon


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Ungibbable mod for Doom 3 BFG Hi Def addon

Corpses stay in the Ungibbable mod converted to work with Doom 3 BFG Hi Def and RBDoom3bfg. Unzip to your Doom ...
 |

 |

 |



    On Saturday, October 30, 2021, 10:22:59 PM EDT, Alex ***@***.***> wrote:  
 
 


I would like to be able to disable gibbing from when you shot bodies on the ground and such. Is there a way to do this already?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by y2keeth** [comment]
did you find that mod?

**Comment by ROCKNROLLKID** [comment]
Yes I know the mod you are talking about. Thank you.
