### ISSUE TITLE
Player shadow, PCSS/CHS support, Baked shadow maps

### ISSUE THREAD

**Issue by DropsMJay** [RobertBeckebans/RBDOOM-3-BFG#680]
Can you make the player model generate shadows? Besides Soft shadows, how about NVidia's PCSS and/or AMD CHS for more realistic shadows. The Shadowmapping feature takes a lot of FPS, can you make the game use baked shadowmaps instead real time ones?

Thanks for you hard work.

**Comment by Calinou** [comment]
> The Shadowmapping feature takes a lot of FPS, can you make the game use baked shadowmaps instead real time ones?

See https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/395. That said, the whole point of Doom 3 is that it uses real-time lighting solutions as opposed to baked lighting solutions.

**Comment by RobertBeckebans** [comment]
I would rather reintroduce some kind of spherical harmonic lightmaps instead of baking shadowmaps. However this is only interesting for people who aim total conversion development with this engine. In the future shadowmap sampling will be distributed over time using the already working temporal anti aliasing in the 635-nvrhi3 branch.
