### ISSUE TITLE
[Feature Request] support of Quake 4 / Prey (2006)

### ISSUE THREAD

**Issue by r-a-sattarov** [RobertBeckebans/RBDOOM-3-BFG#815]
Hi everybody. It is interesting to know how difficult\possible it can be to add support for Quake 4 or Prey (2006) games to RBDOOM-3-BFG?
There were projects ([Quake4Doom](https://github.com/jmarshall23/Quake4Doom), [PreyDoom](https://github.com/jmarshall23/PreyDoom)) that support these games in their engines. Moreover, there is a [project](https://github.com/glKarin/com.n0n3m4.diii4a) that ported these games to the Android platform.

**Comment by RobertBeckebans** [comment]
Well Quake 4 and Prey was ported regardless of the license incompatibility. id Software never released those games under the GPL license and their SDK license is very restricting. I know that Justin Marshall ported those in an attempt to convince Bethesda to release the code but it never happened. Also both ports are unfinished. Quake 4 misses the particle effects because those couldn't be reversed engineered and Prey only worked with the first few maps or just the demo.
Well technically the BFG game code is almost 1:1 to the vanilla Doom 3 game code. The major differences are just the replacement of .gui files for the main menu using Flash and implementing the logic of the menus in C++ and network code is slightly different and coupled to a lobby system.

So it is possible to repeat the porting efforts with the BFG code but I won't do or maintain it because of the license issues.

**Comment by r-a-sattarov** [comment]
Danke, Robert. Thank you for the detailed answer 👍

**Comment by ericwomer** [comment]
Will see what happens when M$ officially owns Bethesda, could try again to ask them to release the code for those games. I donn't see why they wouldn't, unless there was some backroom licensing deals, mainly with Prey (2006) being a better version then the newer one.
