### ISSUE TITLE
240 FPS

### ISSUE THREAD

**Issue by Terepin** [RobertBeckebans/RBDOOM-3-BFG#872]
The original game supports framerate up to 240, but RBDOOM is still limited to only 120. Are you planning to implement 240 FPS as well?

**Comment by Calinou** [comment]
This is already supported using the `com_engineHz 240` console command. It's not exposed to the settings menu yet though.

**Comment by RobertBeckebans** [comment]
It's actually not so easy to reach stable 120Hz with the new rendering features we added to the engine.
It's a different situation with vanilla Doom 3 BFG because the renderer is way more simpler but I don't want to sacrifice features in order to get 240Hz going. So it is a no but as Calinou stated you can fiddle with the com_engineHz setting.
