### ISSUE TITLE
Add support for Mouse4 and Mouse5 in Linux

### ISSUE THREAD

**Issue by slacka** [RobertBeckebans/RBDOOM-3-BFG#89]
In Doom 3,  when you go to settings and try to bind the 4th and 5 mouse buttons, a "?" is displayed instead of MOUSE4 or MOUSE5.  After binding, using the buttons produces no response in game.

In **sdl_events.cpp**, I tried adding 

```
                    case SDL_BUTTON_X1:
						res.evValue = K_MOUSE4;
						mouse_polls.Append( mouse_poll_t( M_ACTION4, ev.button.state == SDL_PRESSED ? 1 : 0 ) );
						break;

                     case SDL_BUTTON_X2:
						res.evValue = K_MOUSE5;
						mouse_polls.Append( mouse_poll_t( M_ACTION5, ev.button.state == SDL_PRESSED ? 1 : 0 ) );
						break;
```
But it did not fix the issue. I'm unfamiliar with this code base, and the issue probably lies elsewhere.  Under Mint 16, I have no issue with mapping these buttons on my MX 518 in other ioquake3 based games like Open Arena.

In **SDL_mouse.h** we have **"#define SDL_BUTTON_X1		6"** and both **K_MOUSE4** and **M_ACTION4** are enum's in **sys_public.h**. Any idea what I'm missing here?

Update: This appears to be a Linux specific bug. When I compiled the vs2013-32bit code on my Win 7 box, I was able to bind and use the 2 thumb buttons on my mouse.

**Comment by DanielGibson** [comment]
I (mostly) fixed this problem in opentech: https://github.com/OpenTechEngine/OpenTechBFG/commit/f19230cfa6539e5d2be399ec5f5516c3dee0d5ee

One small issue is that, even though the buttons are assignable, the doom3bfg control settings just show "????" instead of "Mouse 4" or something.  
I might investigate that problem a bit more when I have some time and prepare a pull request.
